# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d3436e8500f9bbcf3b7c8262667c17d9f6558abcbba3232375165f017e34bd0c78105826075a620bca3cddcd976c69430533832b813d8147d5d883ce241217

test:
  secret_key_base: 558358486d0d8ab010ccb97d2bc7937a0911e2fcf7f87f0a0e995691e4054dcb74220e47eae875c5d4f3f19667a7528a823e8c38686d96be0586b87c5435ef1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
